# Generated by Django 4.2.13 on 2024-05-20 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0004_studentapplication_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplication',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workstatus',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_statuses', to='workapp.studentapplication'),
        ),
    ]
