# Generated by Django 4.2.13 on 2024-05-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0005_alter_studentapplication_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postingplace',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
