# Generated by Django 4.2.13 on 2024-05-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0007_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='matric_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
