# Generated by Django 4.2.13 on 2024-05-28 19:18

from django.db import migrations, models
import workapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0008_alter_user_matric_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='area_of_interest',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='date_signed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='hod_recommendation_signature',
            field=models.FileField(blank=True, default=workapp.models.default_hod_signature, null=True, upload_to='hod_signatures/'),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='reason_for_desiring_to_work',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='room_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='signature',
            field=models.FileField(blank=True, default=workapp.models.default_signature, null=True, upload_to='signatures/'),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='student_photo',
            field=models.ImageField(blank=True, default=workapp.models.default_student_photo, null=True, upload_to='student_photos/'),
        ),
        migrations.AddField(
            model_name='user',
            name='faculty',
            field=models.CharField(blank=True, default='Science', max_length=100, null=True),
        ),
    ]
