# Generated by Django 4.2.13 on 2024-05-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0009_studentapplication_area_of_interest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact_address',
            field=models.TextField(blank=True, default='Ogun State', null=True),
        ),
    ]
