# Generated by Django 4.2.13 on 2024-05-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0016_alter_user_staff_id_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplication',
            name='room_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
