# Generated by Django 4.2.13 on 2024-06-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0017_alter_studentapplication_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='course_of_study',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
