# Generated by Django 4.2.13 on 2024-06-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0019_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default='new_user', max_length=20, null=True),
        ),
    ]
