# Generated by Django 4.2.13 on 2024-06-06 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0020_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentapplication',
            old_name='hod_recommendation_signature',
            new_name='hod_recommendation_letter',
        ),
    ]
