# Generated by Django 4.2.13 on 2024-06-06 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0021_rename_hod_recommendation_signature_studentapplication_hod_recommendation_letter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentapplication',
            options={'ordering': [models.Case(models.When(status='pending', then=models.Value(0)), models.When(status='approved', then=models.Value(1)), models.When(status='rejected', then=models.Value(2)), output_field=models.IntegerField())]},
        ),
        migrations.AlterField(
            model_name='postingplace',
            name='location',
            field=models.CharField(blank=True, default='School Campus', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='postingplace',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
