# Generated by Django 4.2.13 on 2024-06-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0022_alter_studentapplication_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplication',
            name='year_of_study',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
