# Generated by Django 4.2.13 on 2021-01-01 01:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0024_alter_postingplace_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstatus',
            name='student_checked_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
