# Generated by Django 4.2.13 on 2021-01-01 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0025_workstatus_student_checked_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstatus',
            name='student_checked_date',
            field=models.DateTimeField(null=True),
        ),
    ]
