# Generated by Django 4.2.13 on 2024-06-08 07:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0027_alter_workstatus_checked_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workstatus',
            old_name='supervisor_checked',
            new_name='supervisor_approval',
        ),
        migrations.RemoveField(
            model_name='workstatus',
            name='checked_date',
        ),
        migrations.RemoveField(
            model_name='workstatus',
            name='student_checked_date',
        ),
        migrations.RemoveField(
            model_name='workstatus',
            name='week_number',
        ),
        migrations.AddField(
            model_name='workstatus',
            name='comments',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='workstatus',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workstatus',
            name='day',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='workstatus',
            name='supervisor_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workstatus',
            name='time',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
