# Generated by Django 4.2.13 on 2024-06-12 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0029_user_username_or_matric_or_staff_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username_or_matric_or_staff_id',
            new_name='username_or_staff_id',
        ),
    ]
