# Generated by Django 4.2.13 on 2024-06-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0031_remove_user_username_or_staff_id_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstatus',
            name='supervisor_comment',
            field=models.TextField(null=True),
        ),
    ]
