# Generated by Django 4.2.13 on 2024-06-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0032_workstatus_supervisor_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workstatus',
            old_name='time',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='workstatus',
            name='start_time',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
