# Generated by Django 4.2.13 on 2024-06-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0033_rename_time_workstatus_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstatus',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
