# Generated by Django 4.2.13 on 2024-07-10 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0034_alter_workstatus_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workstatus',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='supervisor_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, null=True),
        ),
    ]
