# Generated by Django 4.2.13 on 2024-07-10 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0035_alter_workstatus_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='supervisor_approval',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
