# Generated by Django 4.2.13 on 2024-07-10 08:06

from django.db import migrations, models
import workapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0036_studentapplication_supervisor_approval'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-registration_date']},
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='payment_receipt',
            field=models.ImageField(blank=True, default=workapp.models.default_receipt, null=True, upload_to='receipts/'),
        ),
    ]
